CDAP-15644: Added BigQuery integration tests.
AntonGensitskiy/cdap-integration-tests pull request #1
Opened 2019-07-19 17:43 UTC by AntonGensitskiy

JIRA: https://issues.cask.co/browse/CDAP-15644

In scope of this PR:
* Was added base BigQuery integration tests.

2019-07-22 11:18 UTC, aonischuk requested changes

2019-07-22 11:18 UTC, aonischuk commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/GoogleBigQueryTest.java
> +  private boolean isExisting(String tableId) {
Can we call this `private boolean exists(String tableId)` seems like more grammatically correct. This how the method is called in File API for checking if file exists.

2019-07-22 11:18 UTC, aonischuk commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/GoogleBigQueryTest.java
> +  private static List<FieldValue> getResultTableDate(TableId tableId) {
getResultTableData

2019-07-22 11:18 UTC, aonischuk commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/GoogleBigQueryTest.java
> +      Assert.assertEquals(expectedResult.get(i).getValue(), result.get(i).getValue());
Can we throw a bit more informative exception here. Like which attribute has different values.

Also I see you check these in loop is that guaranteed that the FieldValues are in the same order?

2019-07-22 11:18 UTC, aonischuk commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/GoogleBigQueryTest.java
> +      Assert.assertEquals(expectedResult.get(i).getValue(), result.get(i).getValue());
the same

2019-07-22 11:18 UTC, aonischuk commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/GoogleBigQueryTest.java
> +  private static final String SOURCE_PATH = "src" + System.getProperty("file.separator") + "test"
Can we use `Thread.currentThread().getContextClassLoader().getResource(path);` instead?
Usually this is how resource files are read.

2019-07-22 11:18 UTC, aonischuk commented on pom.xml
> +      <version>1.36.0</version>
Any reason for using older version? Instead of 1.83.0

2019-07-23 14:24 UTC, aielchiieva commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/GoogleBigQueryTest.java
> +  public void test_01_ReadDataAndStoreInNewTable() throws Exception {
Please remove numbers from units test names: `test_01_ReadDataAndStoreInNewTable` -> `testReadDataAndStoreInNewTable`

2019-07-23 14:24 UTC, aielchiieva commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/GoogleBigQueryTest.java
> +    insertData(bigQueryDataset, sourceTableName, Paths.get(SOURCE_PATH + "simple_source.json"));
`Paths.get(SOURCE_PATH, "simple_source.json")`

2019-07-23 14:24 UTC, aielchiieva commented on integration-test-remote/src/test/resources/full_source.json
> +{"string_value": "string_1","int_value": 1,"float_value": 0.1,"boolean_value": true,"numeric_value": 123.456,"timestamp_value": "2014-08-01 12:41:35.220000+00:00","date_value": "2014-08-01","time_val
When writing tests for Datastore during code review I was asked to remove JSON files and store data in class, please check Datastore tests.

2019-08-12 17:04 UTC, closed without merging